name: QUIC Interop AWS-LC

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone docker image definition
        run: |
          git clone -b aws-lc https://github.com/haproxytech/haproxy-qns

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: haproxy-qns
          push: true
          tags: ghcr.io/${{ github.repository }}:aws-lc


  run:
    needs: build
    strategy:
      matrix:
        suite: [
          { client: picoquic, tests: "handshakeloss,handshakecorruption" }
        ]
      fail-fast: false

    name: ${{ matrix.suite.client }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tshark
        run: |
          sudo apt-get update
          sudo apt-get -y install tshark

      - name: Pull image
        run: |
          docker pull ghcr.io/${{ github.repository }}:aws-lc

      - name: Run
        run: |
          git clone https://github.com/quic-interop/quic-interop-runner
          cd quic-interop-runner
          pip install -r requirements.txt --break-system-packages
          python run.py -l logs -r haproxy=ghcr.io/${{ github.repository }}:aws-lc -c ${{ matrix.suite.client }} -s haproxy

      - name: Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: quic-interop-runner/logs/
